In [1]:
import pandas as pd
import numpy as np

In [2]:
clip_starts = np.array([0,  5, 15, 25, 30])
clip_ends   = np.array([4, 14, 24, 29, 35])
segs_arr = np.arange(0, 36)

In [3]:
clip_id = np.searchsorted(clip_starts, segs_arr, side='right') - 1

In [4]:
segs_df = pd.DataFrame({'clip_id': clip_id}, index=segs_arr)
segs_df

    clip_id
0         0
1         0
2         0
3         0
4         0
5         1
6         1
7         1
8         1
9         1
10        1
11        1
12        1
13        1
14        1
15        2
16        2
17        2
18        2
19        2
20        2
21        2
22        2
23        2
24        2
25        3
26        3
27        3
28        3
29        3
30        4
31        4
32        4
33        4
34        4
35        4

In [10]:
# With pandas
clips = pd.DataFrame({'start_seg': clip_starts, 'end_seg': clip_ends})

segs = pd.DataFrame({'feature1': np.arange(100, 100+len(segs_arr)), 'feature2': np.arange(200, 200+len(segs_arr))}, index=segs_arr)
segs.loc[4, 'feature1'] = pd.NA

clip_id = np.searchsorted(clips['start_seg'], segs.index, side='right') - 1
segs['clip_id'] = clip_id
segs

    feature1  feature2  clip_id
0      100.0       200        0
1      101.0       201        0
2      102.0       202        0
3      103.0       203        0
4        NaN       204        0
5      105.0       205        1
6      106.0       206        1
7      107.0       207        1
8      108.0       208        1
9      109.0       209        1
10     110.0       210        1
11     111.0       211        1
12     112.0       212        1
13     113.0       213        1
14     114.0       214        1
15     115.0       215        2
16     116.0       216        2
17     117.0       217        2
18     118.0       218        2
19     119.0       219        2
20     120.0       220        2
21     121.0       221        2
22     122.0       222        2
23     123.0       223        2
24     124.0       224        2
25     125.0       225        3
26     126.0       226        3
27     127.0       227        3
28     128.0       228        3
29     129.0       229        3
30     130.0       230        4
31     131.0       231        4
32     132.0       232        4
33     133.0       233        4
34     134.0       234        4
35     135.0       235        4

In [11]:
# Exclude nan values
has_na = segs['feature1'].isna().groupby(segs['clip_id']).any()
has_na

clip_id
0     True
1    False
2    False
3    False
4    False
Name: feature1, dtype: bool

In [13]:
medians = segs.groupby('clip_id').median()
medians

         feature1  feature2
clip_id
0           101.5     202.0
1           109.5     209.5
2           119.5     219.5
3           127.0     227.0
4           132.5     232.5

In [15]:
medians[has_na] = pd.NA
medians

         feature1  feature2
clip_id
0             NaN       NaN
1           109.5     209.5
2           119.5     219.5
3           127.0     227.0
4           132.5     232.5

In [16]:
clips['feature1'] = medians['feature1']
clips

   start_seg  end_seg  feature1
0          0        4       NaN
1          5       14     109.5
2         15       24     119.5
3         25       29     127.0
4         30       35     132.5