In [1]:
import pandas as pd
from pathlib import Path
from config import PATHS
from helpers import rename_patient

In [2]:
# Paths
# on server:
in_path = PATHS.per_patient_comparison_table.pickle  # on server
out_path = Path("~/thesis_data/tables/copes_table.tex").expanduser()

# local:
# in_path = Path('~/thesis_files/statistical_results/.per_patient.pkl').expanduser()  # local
# out_path = Path('~/Developer/MastersThesis/src/tables/copes_table.tex').expanduser()

In [5]:
comp = pd.read_pickle(in_path)
# comp

In [4]:
t = comp['corr_of_pred_errors'].copy()
t

split             train      test
patient
competition-1  0.853414  0.880122
competition-2  0.808760  0.739500
competition-3  0.853980  0.849131
U002-DE01-01   0.821004  0.822417
U002-DE01-03   0.671090  0.561897
U002-DE01-04   0.514272  0.412429
U002-DE01-05   0.804766  0.812181
U002-DE01-07   0.854925  0.901007
U002-DE01-12   0.490606  0.345045
U002-DE01-15   0.725209  0.762821
U002-DE01-16   0.695311  0.679250
U002-DE01-17   0.830183  0.826612

In [13]:
test = t['test'].copy()
test *= 100
print('Mean:', test.mean().round())
print('Min :', test.min().round())
print('Max :', test.max().round())

Mean: 72.0
Min : 35.0
Max : 90.0

In [23]:
t.index = t.index.map(rename_patient).rename('Patient')
t = t.reset_index(drop=False)
t.columns.name = None
t = t.rename(columns={'train': 'Train', 'test': 'Test'})
t.columns = [r'\textbf{{{}}}'.format(str(c)) for c in t.columns]
t

   \textbf{Patient}  \textbf{Train}  \textbf{Test}
0               C01        0.853414       0.880122
1               C02        0.808760       0.739500
2               C03        0.853980       0.849131
3               U01        0.821004       0.822417
4               U03        0.671090       0.561897
5               U04        0.514272       0.412429
6               U05        0.804766       0.812181
7               U07        0.854925       0.901007
8               U12        0.490606       0.345045
9               U15        0.725209       0.762821
10              U16        0.695311       0.679250
11              U17        0.830183       0.826612

In [24]:
t.to_latex(
    out_path,
    index=False,
    float_format='%.3f'
)