In [1]:
from pathlib import Path
import pandas as pd

from config import PATHS
from written_thesis.helpers import rename_patient

In [2]:
# Paths
# on server:
in_path = PATHS.patient_info_exact.pickle
out_path = Path("~/thesis_data/tables/patient_inclusion.tex").expanduser()

# local:
in_path = Path("~/thesis_files/patient_info/.patient_info_exact.pkl").expanduser()
out_path = Path('~/Developer/MastersThesis/src/tables/patient_inclusion.tex').expanduser()

In [3]:
orig = pd.read_pickle(in_path)

# Keep only real patients (exclude names containing "FAKE")
patient_names = orig.index.get_level_values("patient")
orig = orig[~patient_names.str.contains("FAKE", regex=False)]
orig.head()

                           valid  total_seizures  valid_seizures  \
dataset     patient
competition competition-1   True              92              58
            competition-2   True              54              53
            competition-3   True              63              63
ultra2      U002-DE01-01    True             259             195
            U002-DE01-03    True              59              52

                           enough_valid_seizures    recordings_start  \
dataset     patient
competition competition-1                   True 2020-11-04 14:26:59
            competition-2                   True 2020-12-09 15:07:12
            competition-3                   True 2022-01-24 15:48:13
ultra2      U002-DE01-01                    True 2021-05-15 08:09:47
            U002-DE01-03                    True 2021-06-04 10:36:37

                               recordings_end          timespan  \
dataset     patient
competition competition-1 2022-03-14 12:03:53 494 days 21:36:54
            competition-2 2022-05-31 11:29:50 537 days 20:22:38
            competition-3 2023-03-16 05:18:29 415 days 13:30:16
ultra2      U002-DE01-01  2022-06-21 07:10:33 401 days 23:00:46
            U002-DE01-03  2022-07-03 22:48:33 394 days 12:11:56

                          duration_recorded duration_not_recorded  \
dataset     patient
competition competition-1 388 days 06:45:21     106 days 14:51:33
            competition-2 487 days 03:57:57      50 days 16:24:41
            competition-3 394 days 16:38:57      20 days 20:51:19
ultra2      U002-DE01-01  381 days 07:46:51      20 days 15:13:55
            U002-DE01-03  295 days 19:25:23      98 days 16:46:33

                           ratio_recorded  valid_ratio_recorded
dataset     patient
competition competition-1        0.784565                  True
            competition-2        0.905766                  True
            competition-3        0.949781                  True
ultra2      U002-DE01-01         0.948665                  True
            U002-DE01-03         0.749818                  True

In [4]:
patient_level = orig.index.names.index("patient")
renamed_patient_levels = orig.index.levels[patient_level].map(rename_patient)
orig.index = orig.index.set_levels(renamed_patient_levels, level="patient")

orig

                     valid  total_seizures  valid_seizures  \
dataset     patient
competition C01       True              92              58
            C02       True              54              53
            C03       True              63              63
ultra2      U01       True             259             195
            U03       True              59              52
            U04       True              64              62
            U05       True              76              68
            U07       True              13              13
            U12       True              37              30
            U15       True              30              23
            U16       True              16              16
            U17       True              21              21
            U02      False               2               2
            U06      False               0               0
            U08      False               9               7
            U09      False               0               0
            U10      False               0               0
            U11      False               0               0
            U13      False               4               4
            U14      False               5               3
            U18      False               4               4
            U19      False               8               8
            U20      False               6               6
            U21      False              24              22
            U22      False               3               3
            U23      False              15              11
            U24      False               4               2

                     enough_valid_seizures    recordings_start  \
dataset     patient
competition C01                       True 2020-11-04 14:26:59
            C02                       True 2020-12-09 15:07:12
            C03                       True 2022-01-24 15:48:13
ultra2      U01                       True 2021-05-15 08:09:47
            U03                       True 2021-06-04 10:36:37
            U04                       True 2021-10-04 10:31:01
            U05                       True 2021-11-22 15:42:30
            U07                       True 2022-02-16 10:14:30
            U12                       True 2023-02-13 17:18:58
            U15                       True 2024-03-18 16:26:02
            U16                       True 2024-02-23 16:58:20
            U17                       True 2024-09-20 14:30:41
            U02                      False 2021-05-18 12:59:54
            U06                      False 2022-02-01 12:35:40
            U08                      False 2022-03-18 11:19:03
            U09                      False 2022-04-25 09:43:43
            U10                      False 2022-09-23 15:35:22
            U11                      False 2022-10-07 16:45:53
            U13                      False 2023-08-21 16:43:06
            U14                      False 2023-11-13 16:17:07
            U18                      False 2024-10-01 14:23:56
            U19                      False                 NaT
            U20                      False                 NaT
            U21                       True                 NaT
            U22                      False 2025-05-12 16:00:21
            U23                       True                 NaT
            U24                      False                 NaT

                         recordings_end          timespan duration_recorded  \
dataset     patient
competition C01     2022-03-14 12:03:53 494 days 21:36:54 388 days 06:45:21
            C02     2022-05-31 11:29:50 537 days 20:22:38 487 days 03:57:57
            C03     2023-03-16 05:18:29 415 days 13:30:16 394 days 16:38:57
ultra2      U01     2022-06-21 07:10:33 401 days 23:00:46 381 days 07:46:51
            U03     2022-07-03 22:48:33 394 days 12:11:56 295 days 19:25:23
            U04     2022-04-20 08:19:10 197 days 21:48:09 180 days 18:25:04
            U05     2022-11-15 17:17:45 358 days 01:35:15 299 days 12:43:37
            U07     2022-06-28 10:40:10 132 days 00:25:40 124 days 10:58:29
            U12     2023-12-20 12:15:20 309 days 18:56:22 199 days 06:56:38
            U15     2025-03-05 20:24:52 352 days 03:58:50 308 days 12:00:28
            U16     2025-02-04 05:55:59 346 days 12:57:39 222 days 17:34:32
            U17     2025-06-12 06:18:04 264 days 15:47:23 248 days 06:01:32
            U02     2022-03-08 10:19:31 293 days 21:19:37 102 days 01:10:07
            U06     2022-05-06 08:53:29  93 days 20:17:49  84 days 17:53:31
            U08     2022-09-14 11:00:50 179 days 23:41:47 137 days 16:22:14
            U09     2023-02-20 13:47:19 301 days 04:03:36 291 days 09:06:01
            U10     2023-04-13 07:07:49 201 days 15:32:27 165 days 10:39:52
            U11     2023-05-12 07:44:04 216 days 14:58:11 155 days 21:31:45
            U13     2024-03-10 20:06:49 202 days 03:23:43 115 days 10:44:36
            U14     2025-01-07 07:14:40 420 days 14:57:33 398 days 16:55:04
            U18     2025-04-30 09:54:12 210 days 19:30:16 188 days 08:19:30
            U19                     NaT   0 days 00:00:00   0 days 00:00:00
            U20                     NaT   0 days 00:00:00   0 days 00:00:00
            U21                     NaT   0 days 00:00:00   0 days 00:00:00
            U22     2025-05-16 10:25:52   3 days 18:25:31   3 days 08:33:23
            U23                     NaT   0 days 00:00:00   0 days 00:00:00
            U24                     NaT   0 days 00:00:00   0 days 00:00:00

                    duration_not_recorded  ratio_recorded  \
dataset     patient
competition C01         106 days 14:51:33        0.784565
            C02          50 days 16:24:41        0.905766
            C03          20 days 20:51:19        0.949781
ultra2      U01          20 days 15:13:55        0.948665
            U03          98 days 16:46:33        0.749818
            U04          17 days 03:23:05        0.913389
            U05          58 days 12:51:38        0.836522
            U07           7 days 13:27:11        0.942731
            U12         110 days 11:59:44        0.643306
            U15          43 days 15:58:22        0.876009
            U16         123 days 19:23:07        0.642732
            U17          16 days 09:45:51        0.938007
            U02         191 days 20:09:30        0.347236
            U06           9 days 02:24:18        0.903030
            U08          42 days 07:19:33        0.764954
            U09           9 days 18:57:35        0.967493
            U10          36 days 04:52:35        0.820463
            U11          60 days 17:26:26        0.719667
            U13          86 days 16:39:07        0.571123
            U14          21 days 22:02:29        0.947891
            U18          22 days 11:10:46        0.893432
            U19           0 days 00:00:00        0.000000
            U20           0 days 00:00:00        0.000000
            U21           0 days 00:00:00        0.000000
            U22           0 days 09:52:08        0.890861
            U23           0 days 00:00:00        0.000000
            U24           0 days 00:00:00        0.000000

                     valid_ratio_recorded
dataset     patient
competition C01                      True
            C02                      True
            C03                      True
ultra2      U01                      True
            U03                      True
            U04                      True
            U05                      True
            U07                      True
            U12                      True
            U15                      True
            U16                      True
            U17                      True
            U02                     False
            U06                      True
            U08                      True
            U09                      True
            U10                      True
            U11                      True
            U13                     False
            U14                      True
            U18                      True
            U19                     False
            U20                     False
            U21                     False
            U22                      True
            U23                     False
            U24                     False

In [5]:
no_edfs_mask = orig['recordings_start'].isna()
no_edfs = orig[no_edfs_mask]
has_edfs = orig[~no_edfs_mask].copy()
print('No EDFs, excluding: ', no_edfs.index.get_level_values('patient').to_list())
no_edfs

No EDFs, excluding:  ['U19', 'U20', 'U21', 'U23', 'U24']

                 valid  total_seizures  valid_seizures  enough_valid_seizures  \
dataset patient
ultra2  U19      False               8               8                  False
        U20      False               6               6                  False
        U21      False              24              22                   True
        U23      False              15              11                   True
        U24      False               4               2                  False

                recordings_start recordings_end timespan duration_recorded  \
dataset patient
ultra2  U19                  NaT            NaT   0 days            0 days
        U20                  NaT            NaT   0 days            0 days
        U21                  NaT            NaT   0 days            0 days
        U23                  NaT            NaT   0 days            0 days
        U24                  NaT            NaT   0 days            0 days

                duration_not_recorded  ratio_recorded  valid_ratio_recorded
dataset patient
ultra2  U19                    0 days             0.0                 False
        U20                    0 days             0.0                 False
        U21                    0 days             0.0                 False
        U23                    0 days             0.0                 False
        U24                    0 days             0.0                 False

In [6]:
has_edfs

                     valid  total_seizures  valid_seizures  \
dataset     patient
competition C01       True              92              58
            C02       True              54              53
            C03       True              63              63
ultra2      U01       True             259             195
            U03       True              59              52
            U04       True              64              62
            U05       True              76              68
            U07       True              13              13
            U12       True              37              30
            U15       True              30              23
            U16       True              16              16
            U17       True              21              21
            U02      False               2               2
            U06      False               0               0
            U08      False               9               7
            U09      False               0               0
            U10      False               0               0
            U11      False               0               0
            U13      False               4               4
            U14      False               5               3
            U18      False               4               4
            U22      False               3               3

                     enough_valid_seizures    recordings_start  \
dataset     patient
competition C01                       True 2020-11-04 14:26:59
            C02                       True 2020-12-09 15:07:12
            C03                       True 2022-01-24 15:48:13
ultra2      U01                       True 2021-05-15 08:09:47
            U03                       True 2021-06-04 10:36:37
            U04                       True 2021-10-04 10:31:01
            U05                       True 2021-11-22 15:42:30
            U07                       True 2022-02-16 10:14:30
            U12                       True 2023-02-13 17:18:58
            U15                       True 2024-03-18 16:26:02
            U16                       True 2024-02-23 16:58:20
            U17                       True 2024-09-20 14:30:41
            U02                      False 2021-05-18 12:59:54
            U06                      False 2022-02-01 12:35:40
            U08                      False 2022-03-18 11:19:03
            U09                      False 2022-04-25 09:43:43
            U10                      False 2022-09-23 15:35:22
            U11                      False 2022-10-07 16:45:53
            U13                      False 2023-08-21 16:43:06
            U14                      False 2023-11-13 16:17:07
            U18                      False 2024-10-01 14:23:56
            U22                      False 2025-05-12 16:00:21

                         recordings_end          timespan duration_recorded  \
dataset     patient
competition C01     2022-03-14 12:03:53 494 days 21:36:54 388 days 06:45:21
            C02     2022-05-31 11:29:50 537 days 20:22:38 487 days 03:57:57
            C03     2023-03-16 05:18:29 415 days 13:30:16 394 days 16:38:57
ultra2      U01     2022-06-21 07:10:33 401 days 23:00:46 381 days 07:46:51
            U03     2022-07-03 22:48:33 394 days 12:11:56 295 days 19:25:23
            U04     2022-04-20 08:19:10 197 days 21:48:09 180 days 18:25:04
            U05     2022-11-15 17:17:45 358 days 01:35:15 299 days 12:43:37
            U07     2022-06-28 10:40:10 132 days 00:25:40 124 days 10:58:29
            U12     2023-12-20 12:15:20 309 days 18:56:22 199 days 06:56:38
            U15     2025-03-05 20:24:52 352 days 03:58:50 308 days 12:00:28
            U16     2025-02-04 05:55:59 346 days 12:57:39 222 days 17:34:32
            U17     2025-06-12 06:18:04 264 days 15:47:23 248 days 06:01:32
            U02     2022-03-08 10:19:31 293 days 21:19:37 102 days 01:10:07
            U06     2022-05-06 08:53:29  93 days 20:17:49  84 days 17:53:31
            U08     2022-09-14 11:00:50 179 days 23:41:47 137 days 16:22:14
            U09     2023-02-20 13:47:19 301 days 04:03:36 291 days 09:06:01
            U10     2023-04-13 07:07:49 201 days 15:32:27 165 days 10:39:52
            U11     2023-05-12 07:44:04 216 days 14:58:11 155 days 21:31:45
            U13     2024-03-10 20:06:49 202 days 03:23:43 115 days 10:44:36
            U14     2025-01-07 07:14:40 420 days 14:57:33 398 days 16:55:04
            U18     2025-04-30 09:54:12 210 days 19:30:16 188 days 08:19:30
            U22     2025-05-16 10:25:52   3 days 18:25:31   3 days 08:33:23

                    duration_not_recorded  ratio_recorded  \
dataset     patient
competition C01         106 days 14:51:33        0.784565
            C02          50 days 16:24:41        0.905766
            C03          20 days 20:51:19        0.949781
ultra2      U01          20 days 15:13:55        0.948665
            U03          98 days 16:46:33        0.749818
            U04          17 days 03:23:05        0.913389
            U05          58 days 12:51:38        0.836522
            U07           7 days 13:27:11        0.942731
            U12         110 days 11:59:44        0.643306
            U15          43 days 15:58:22        0.876009
            U16         123 days 19:23:07        0.642732
            U17          16 days 09:45:51        0.938007
            U02         191 days 20:09:30        0.347236
            U06           9 days 02:24:18        0.903030
            U08          42 days 07:19:33        0.764954
            U09           9 days 18:57:35        0.967493
            U10          36 days 04:52:35        0.820463
            U11          60 days 17:26:26        0.719667
            U13          86 days 16:39:07        0.571123
            U14          21 days 22:02:29        0.947891
            U18          22 days 11:10:46        0.893432
            U22           0 days 09:52:08        0.890861

                     valid_ratio_recorded
dataset     patient
competition C01                      True
            C02                      True
            C03                      True
ultra2      U01                      True
            U03                      True
            U04                      True
            U05                      True
            U07                      True
            U12                      True
            U15                      True
            U16                      True
            U17                      True
            U02                     False
            U06                      True
            U08                      True
            U09                      True
            U10                      True
            U11                      True
            U13                     False
            U14                      True
            U18                      True
            U22                      True

In [7]:
# Make it pretty
t = has_edfs.copy()
t = t.sort_index().reset_index()
# t = t.assign(valid=t.pop('valid'))  # move valid to the end
t = t.drop(columns=['dataset', 'recordings_start', 'recordings_end', 'duration_not_recorded'])
for col in ['duration_recorded', 'timespan']:
    t[col] = t[col].dt.days  # just show days (not hours)
for col in ['valid', 'enough_valid_seizures', 'valid_ratio_recorded']:
    t[col] = t[col].map({True: r'$\checkmark$', False: r'$\times$'}).astype(str)
t['ratio_recorded'] = (t['ratio_recorded'] * 100).round().astype(int)

assert t.columns.to_list() == ['patient', 'valid', 'total_seizures', 'valid_seizures', 'enough_valid_seizures',
                               'timespan', 'duration_recorded', 'ratio_recorded', 'valid_ratio_recorded']
# Grouped headers
t.columns = pd.MultiIndex.from_tuples([
    ('Patient', 'ID'),
    ('Patient', 'Incl.'),
    ('Seizures', 'Total'),
    ('Seizures', 'Valid'),
    ('Seizures', 'Met'),
    ('Timespan (days)', 'Monitoring'),
    ('Timespan (days)', 'Recorded'),
    ('Timespan (days)', 'Coverage'),
    ('Timespan (days)', 'Met'),
])

t

   Patient               Seizures                     Timespan (days)  \
        ID         Incl.    Total Valid           Met      Monitoring
0      C01  $\checkmark$       92    58  $\checkmark$             494
1      C02  $\checkmark$       54    53  $\checkmark$             537
2      C03  $\checkmark$       63    63  $\checkmark$             415
3      U01  $\checkmark$      259   195  $\checkmark$             401
4      U02      $\times$        2     2      $\times$             293
5      U03  $\checkmark$       59    52  $\checkmark$             394
6      U04  $\checkmark$       64    62  $\checkmark$             197
7      U05  $\checkmark$       76    68  $\checkmark$             358
8      U06      $\times$        0     0      $\times$              93
9      U07  $\checkmark$       13    13  $\checkmark$             132
10     U08      $\times$        9     7      $\times$             179
11     U09      $\times$        0     0      $\times$             301
12     U10      $\times$        0     0      $\times$             201
13     U11      $\times$        0     0      $\times$             216
14     U12  $\checkmark$       37    30  $\checkmark$             309
15     U13      $\times$        4     4      $\times$             202
16     U14      $\times$        5     3      $\times$             420
17     U15  $\checkmark$       30    23  $\checkmark$             352
18     U16  $\checkmark$       16    16  $\checkmark$             346
19     U17  $\checkmark$       21    21  $\checkmark$             264
20     U18      $\times$        4     4      $\times$             210
21     U22      $\times$        3     3      $\times$               3


   Recorded Coverage           Met
0       388       78  $\checkmark$
1       487       91  $\checkmark$
2       394       95  $\checkmark$
3       381       95  $\checkmark$
4       102       35      $\times$
5       295       75  $\checkmark$
6       180       91  $\checkmark$
7       299       84  $\checkmark$
8        84       90  $\checkmark$
9       124       94  $\checkmark$
10      137       76  $\checkmark$
11      291       97  $\checkmark$
12      165       82  $\checkmark$
13      155       72  $\checkmark$
14      199       64  $\checkmark$
15      115       57      $\times$
16      398       95  $\checkmark$
17      308       88  $\checkmark$
18      222       64  $\checkmark$
19      248       94  $\checkmark$
20      188       89  $\checkmark$
21        3       89  $\checkmark$

In [8]:
latex = t.to_latex(
    index=False,
    escape=False,
    formatters={("Timespan (days)", "Coverage"): lambda x: r"\SI{" + str(x) + r"}{\percent}"},
    multicolumn=True,
    multicolumn_format="|c|",
    column_format="|l r|r r r|r r r r|",  # or no vertical bars if using pure booktabs style
)

# Add row color to header rows
lines = latex.split("\n")
in_header = False
new_lines = []
for i, line in enumerate(lines):
    if r"\toprule" in line:
        in_header = True
        new_lines.append(line)
    elif in_header and line.strip().endswith(r"\\"):
        # This is a header row, add \rowcolor
        new_lines.append(r"\rowcolor{gray!25} " + line)
    elif in_header and r"\midrule" in line and i > 0:
        # \midrule marks end of headers
        new_lines.append(line)
        in_header = False
    else:
        new_lines.append(line)
latex = "\n".join(new_lines)

# Replace booktabs rules with standard hlines
latex = latex.replace(r"\toprule", r"\hline").replace(r"\midrule", r"\hline").replace(r"\bottomrule", r"\hline")

# Fix thicker middle vertical lines
latex = (latex
         .replace(r'\multicolumn{3}{|c|}{Seizures}', r'\multicolumn{3}{c|}{Seizures}')
         .replace(r'\multicolumn{4}{|c|}{Timespan (days)}', r'\multicolumn{4}{c|}{Timespan (days)}'))

out_path.write_text(latex, encoding="utf-8")

2247